export const SET_WALLET_ADDRESS = "SET_WALLET_ADDRESS";
export const SET_IS_WALLET_CONNECTED = "SET_IS_WALLET_CONNECTED";
export const SET_WALLET_CHAIN = "SET_WALLET_CHAIN";
export const SET_USER_CHAIN = "SET_USER_CHAIN";